export default {
  it: {
    "dicLineChart.title": "Trend delle dichiarazioni di accessibilità",
    "dicLineChart.SITItitle": "Trend delle dichiarazioni di accessibilità dei siti",
    "dicLineChart.APPtitle": "Trend delle dichiarazioni di accessibilità delle app",
    "dicLineChart.chartDescription": "Il trend delle dichiarazioni di accessibilità riporta l’andamento delle pubblicazioni delle dichiarazioni di accessibilità da parte delle PA per i loro siti web e app nel corso degli anni. Il grafico illustra dal 2020 ad oggi, l’incremento della pubblicazione delle dichiarazioni di accessibilità da parte delle PA.",
    "dicLineChart.tableDescription": "Il trend delle dichiarazioni di accessibilità riporta l’andamento delle pubblicazioni delle dichiarazioni di accessibilità da parte delle PA per i loro siti web e app nel corso degli anni. Il crescente aumento delle dichiarazioni mette in risalto l’impegno preso nel rendere le informazioni fruibili a tutti, senza discriminazioni.",
    "dicLineChart.SITIchartDescription": "Il trend delle dichiarazioni di accessibilità riporta l’andamento delle pubblicazioni delle dichiarazioni di accessibilità da parte delle PA per i loro siti web nel corso degli anni. Il grafico illustra dal 2020 ad oggi, l’incremento della pubblicazione delle dichiarazioni di accessibilità da parte delle PA.",
    "dicLineChart.SITItableDescription": "Il trend delle dichiarazioni di accessibilità riporta l’andamento delle pubblicazioni delle dichiarazioni di accessibilità da parte delle PA per i loro siti web nel corso degli anni. Il crescente aumento delle dichiarazioni mette in risalto l’impegno preso nel rendere le informazioni fruibili a tutti, senza discriminazioni.",
    "dicLineChart.APPchartDescription": "Il trend delle dichiarazioni di accessibilità riporta l’andamento delle pubblicazioni delle dichiarazioni di accessibilità da parte delle PA per le loro applicazioni mobile nel corso degli anni. Il grafico illustra dal 2020 ad oggi, l’incremento della pubblicazione delle dichiarazioni di accessibilità da parte delle PA.",
    "dicLineChart.APPtableDescription": "Il trend delle dichiarazioni di accessibilità riporta l’andamento delle pubblicazioni delle dichiarazioni di accessibilità da parte delle PA per le loro applicazioni mobile nel corso degli anni. Il crescente aumento delle dichiarazioni mette in risalto l’impegno preso nel rendere le informazioni fruibili a tutti, senza discriminazioni.",
    "dicLineChart.halfTitle": "Dati generali",
    "dicLineChart.anno": "Anno",
    "dicLineChart.label": "Dichiarazioni",
    "dicLineChart.numero": "Numero Dichiarazioni",
    "dicLineChart.numeroSITI": "Dichiarazioni Web",
    "dicLineChart.numeroAPP": "Dichiarazioni App",
    },
  en: {
    "dicLineChart.title": "Accessibility statements trend",
    "dicLineChart.SITItitle": "Websites accessibility statements trend",
    "dicLineChart.APPtitle": "App accessibility statements trend",
    "dicLineChart.chartDescription": "The trend of accessibility statements reflects the trend in the publication of accessibility statements by Public Administrations (PAs) for their websites and apps over the years. The graph illustrates the increase in the publication of accessibility statements by PAs from 2020 to the present.",
    "dicLineChart.tableDescription": "The trend of accessibility statements reflects the trend in the publication of accessibility statements by Public Administrations (PAs) for their websites and apps over the years. The increasing number of statements highlights the commitment to making information accessible to everyone without discrimination.",
    "dicLineChart.SITIchartDescription": "The trend of accessibility statements reflects the trend in the publication of accessibility statements by Public Administrations (PAs) for their websites over the years. The graph illustrates the increase in the publication of accessibility statements by PAs from 2020 to the present.",
    "dicLineChart.SITItableDescription": "The trend of accessibility statements reflects the trend in the publication of accessibility statements by Public Administrations (PAs) for their websites over the years. The increasing number of statements highlights the commitment to making information accessible to everyone without discrimination.",
    "dicLineChart.APPchartDescription": "The trend of accessibility statements reflects the trend in the publication of accessibility statements by Public Administrations (PAs) for their mobile applications over the years. The graph illustrates the increase in the publication of accessibility statements by PAs from 2020 to the present.",
    "dicLineChart.APPtableDescription": "The trend of accessibility statements reflects the trend in the publication of accessibility statements by Public Administrations (PAs) for their mobile applications over the years. The increasing number of statements highlights the commitment to making information accessible to everyone without discrimination.",
    "dicLineChart.halfTitle": "General data",
    "dicLineChart.anno": "Year",
    "dicLineChart.label": "Statements",
    "dicLineChart.numero": "Accessibility statements published",
    "dicLineChart.numeroSITI": "Web statements",
    "dicLineChart.numeroAPP": "App statements",
  },
};
