export default {
  it: {
    "erroriMain.title": "Errori di accessibilità",
    "erroriMain.latestUpdate": "Ultimo aggiornamento dati: {{ultimoAggiornamento}}",
    "erroriMain.subtitleSemp": "Gli errori di accessibilità identificabili automaticamente",
    "erroriMain.subtitleAppMain": "Gli errori di accessibilità rilevati dal controllo manuale nei siti web",
    "erroriMain.subtitleAppHalf": "Gli errori di accessibilità riscontrati dal controllo manuale delle APP",
    "erroriMain.descriptionSemp": "Gli indicatori e l’analisi automatica dell’accessibilità sono strutturati sulla base delle conformità alle prescrizioni individuate nella norma EN 301 549. {{break}} MAUVE++ analizza la ricorrenza degli errori su {{numero}} dei 50 criteri di successo previsti dalle linee guida, realizzando in tal modo un’analisi parziale. {{break}} Scopri di più sulle",
    "erroriMain.descriptionAppMain": "Attraverso il conteggio dei punti di controlli previsti all’interno del prospetto A.1 (norma UNI CEI EN 301549 vigente) soddisfatti o meno nell'ambito dei criteri applicabili è possibile desumere “la conformità”, “la parziale conformità” o la “non conformità”.{{doubleBreak}} Il servizio è “conforme“ se non è stato rilevato alcun errore, “parzialmente conforme“ se i punti di controllo soddisfatti sono superiori al 50% e inferiori al 100%. Un sito è “non conforme“ se gli errori superano il 50% nell' ambito dei criteri applicabili.{{doubleBreak}} Nel conteggio della conformità del sito web sono inclusi i documenti inseriti all’interno delle singole pagine web del campione. {{break}} Scopri di più sulle",
    "erroriMain.descriptionAppHalf": "Attraverso il conteggio dei punti di controlli previsti all’interno del prospetto A.2 (norma UNI CEI EN 301549 vigente) soddisfatti o meno nell'ambito dei criteri applicabili è possibile desumere “la conformità”, “la parziale conformità” o la “non conformità”.{{doubleBreak}} Il servizio è “conforme“ se non è stato rilevato alcun errore, “parzialmente conforme“ se i punti di controllo soddisfatti sono superiori al 50% e inferiori al 100%. Un sito è “non conforme“ se gli errori superano il 50% nell' ambito dei criteri applicabili.{{doubleBreak}} Nel conteggio della conformità del sito web sono inclusi i documenti inseriti all’interno delle singole pagine web del campione. {{break}} Scopri di più sulle",
    "erroriMain.link": "Linee Guida e i Principi delle WCAG 2.1",
    "erroriMain.WCAGlink": "https://www.w3.org/Translations/WCAG21-it/",
  },
  en: {
    "erroriMain.title": "Accessibility errors",
    "erroriMain.latestUpdate": "Last data update: {{ultimoAggiornamento}}",
    "erroriMain.subtitleSemp": "Automatically identifiable accessibility errors",
    "erroriMain.subtitleAppMain": "Accessibility errors detected by manual checking in websites",
    "erroriMain.subtitleAppHalf": "Accessibility errors found by manual checking of APPs",
    "erroriMain.descriptionSemp": "Indicators and automatic accessibility analysis are structured based on compliance with the requirements identified in the EN 301 549 standard. {{break}} MAUVE++ analyzes the occurrence of errors in {{numero}} out of the 50 success criteria outlined in the guidelines, thus conducting a partial analysis. {{break}} Learn more about the",
    "erroriMain.descriptionAppMain": "By counting the control points provided in table A.1 (current UNI CEI EN 301549 standard) whether satisfied or not within the applicable criteria, it is possible to deduce “compliance“, “partial compliance“ or “non-compliance“.{{doubleBreak}} The service is “compliant“ if no errors were detected, “partially compliant“ if the checkpoints satisfied are greater than 50% and less than 100%. A site is “non-compliant“ if the errors exceed 50% within the scope of the applicable criteria.{{doubleBreak}} The documents inserted within the individual web pages of the sample are included in the website's compliance count. {{break}} Learn more about the", 
    "erroriMain.descriptionAppHalf": "By counting the control points provided in table A.2 (current UNI CEI EN 301549 standard) whether satisfied or not within the applicable criteria, it is possible to deduce “compliance“, “partial compliance“ or “non-compliance“.{{doubleBreak}} The service is “compliant“ if no errors were detected, “partially compliant“ if the checkpoints satisfied are greater than 50% and less than 100%. A site is “non-compliant“ if the errors exceed 50% within the scope of the applicable criteria.{{doubleBreak}} The documents inserted within the individual web pages of the sample are included in the website's compliance count. {{break}} Learn more about the",
    "erroriMain.link": "WCAG 2.1 Guidelines and Principles",
    "erroriMain.WCAGlink": "https://www.w3.org/TR/WCAG21/",
  },
};
