export default {
  it: {
    "feedback.cardTitle": "Hai trovato utile questa pagina?",
    "feedback.optionOneConfirmation": "Feedback inviato. Grazie",
    "feedback.optionOne": "Sì",
    "feedback.optionTwo": "No",
    "feedback.sendButton": "Invia feedback",
    "feedback.closeModal": "Chiudi finestra modale",
    "feedback.title": "Grazie della tua risposta!",
    "feedback.subtitle":
      "Aiutaci a migliorare la pagina con qualche dettaglio in più",
    "feedback.description":
      "Le seguenti informazioni sono raccolte in forma anonima e ci aiutano a capire come migliroare la tua esperienza e l’esposizione dei dati senza trattare dati personali.",
    "feedback.questionOne": "Chi sei?",
    "feedback.oneFirst": "Pubblica amministrazione",
    "feedback.oneSecond": "Cittadino",
    "feedback.oneThird": "Giornalista e/o addetto stampa",
    "feedback.oneFourth": "Azienda privata",
    "feedback.oneFifth": "Altro",
    "feedback.questionTwo": "Hai trovato questa pagina grazie a: ",
    "feedback.twoFirst": "Motore di ricerca",
    "feedback.twoSecond": "Messaggio e/o post social",
    "feedback.twoThird": "Navigazione del sito",
    "feedback.twoFourth": "Altro sito web",
    "feedback.twoFifth": "Altro",
    "feedback.questionThree": "Come possiamo migliorare la pagina?",
    "feedback.threeFirst": "Inserisci qui il tuo testo",
  },
  en: {
    "feedback.cardTitle": "Did you find this page helpful?",
    "feedback.optionOneConfirmation": "Your feedback has been sent. Thank you",
    "feedback.optionOne": "Yes",
    "feedback.optionTwo": "No",
    "feedback.sendButton": "Send feedback",
    "feedback.closeModal": "Close modal",
    "feedback.title": "Thank you for your response!",
    "feedback.subtitle": "Help us improve the page with some additional details.",
    "feedback.description": "The following information is collected anonymously and helps us understand how to enhance your experience and data presentation without processing personal data.",
    "feedback.questionOne": "Who are you?",
    "feedback.oneFirst": "Public Administration",
    "feedback.oneSecond": "Citizen",
    "feedback.oneThird": "Journalist and/or press officer ",
    "feedback.oneFourth": "Private company",
    "feedback.oneFifth": "Other",
    "feedback.questionTwo": "How did you find this page?",
    "feedback.twoFirst": "Search engine",
    "feedback.twoSecond": "Message and/or social post ",
    "feedback.twoThird": "Website navigation",
    "feedback.twoFourth": "Another website",
    "feedback.twoFifth": "Other",
    "feedback.questionThree": "How can we improve the page?",
    "feedback.threeFirst": "Enter your text here",
  },
};
