export default {
  it: {
    "footer.logoUE": "Unione Europea - Next Generation EU",
    "footer.linkUE": "https://next-generation-eu.europa.eu/index_it",
    "footer.logoDTD": "Dipartimento per la trasformazione digitale",
    "footer.linkDTD": "https://innovazione.gov.it/",
    "footer.logoAGID": "AgID - Agenzia per l’Italia Digitale",
    "footer.linkAGID": "https://www.agid.gov.it/",
    "footer.social": "Seguici su",
    "footer.statement": "Dichiarazione di accessibilità",
    "footer.mediaPolicy": "Media policy",
    "footer.mediaPolicyLink": "https://www.agid.gov.it/it/media-policy",
    "footer.legalPolicy": "Note legali",
    "footer.privacyPolicy": "Privacy policy",
    "footer.guidaPiattaforma": "Guida alla piattaforma",
    "footer.contacts": "Contatti",
  },
  en: {
    "footer.logoUE": "European Union - Next Generation EU",
    "footer.linkUE": "https://next-generation-eu.europa.eu/index_en",
    "footer.logoDTD": "Department for Digital Transformation",
    "footer.linkDTD": "https://innovazione.gov.it/",
    "footer.logoAGID": "AgID - Agenzia per l’Italia Digitale",
    "footer.linkAGID": "https://www.agid.gov.it/en",
    "footer.social": "Follow us on",
    "footer.statement": "Accessibility Statement",
    "footer.mediaPolicy": "Media policy",
    "footer.mediaPolicyLink": "https://www.agid.gov.it/en/media-policy-en",
    "footer.legalPolicy": "Legal notice",
    "footer.privacyPolicy": "Privacy policy",
    "footer.guidaPiattaforma": "Guide to the platform",
    "footer.contacts": "Contacts",
  },
};
