export default {
  it: {
    "footer.logoUE": "Unione Europea - Next Generation EU",
    "footer.linkUE": "https://next-generation-eu.europa.eu/index_it",
    "footer.logoDTD": "Dipartimento per la trasformazione digitale",
    "footer.linkDTD": "https://innovazione.gov.it/",
    "footer.logoAGID": "AgID - Agenzia per l’Italia Digitale",
    "footer.linkAGID": "https://www.agid.gov.it/",
    "footer.statement": "Dichiarazione di accessibilità",
    "footer.mediaPolicy": "Media Policy",
    "footer.legalPolicy": "Note legali",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.contacts": "Contatti",
  },
  en: {
    "footer.logoUE": "European Union - Next Generation EU",
    "footer.linkUE": "https://next-generation-eu.europa.eu/index_en",
    "footer.logoDTD": "Department for Digital Transformation",
    "footer.linkDTD": "https://innovazione.gov.it/",
    "footer.logoAGID": "AgID - Agenzia per l’Italia Digitale",
    "footer.linkAGID": "https://www.agid.gov.it/en",
    "footer.statement": "Accessibility Statement",
    "footer.mediaPolicy": "Media Policy",
    "footer.legalPolicy": "Legal notice",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.contacts": "Contacts",
  },
};
