export default {
  it: {
    "header.agid": "Agenzia per l’Italia Digitale",
    "header.agidLink": "https://www.agid.gov.it/",
    "header.language": "Selezione lingua",
    "header.selectedLanguage": "ITA",
    "header.logo": "/logo/Logo Dash Ext ITA.svg",
    "header.monitoraggio": "Logo del sito web Monitoraggio Accessibilità",
    "header.monitoraggioBadge": "beta",
    "header.tabHome": "Home",
    "header.tabMonitoraggio": "Monitoraggio",
    "header.tabMonSemplificato": "Monitoraggio semplificato",
    "header.tabMonApprofondito": "Monitoraggio approfondito",
    "header.tabErrori": "Errori",
    "header.tabErrSemplificato": "Errori monitoraggio semplificato",
    "header.tabErrApprofondito": "Errori monitoraggio approfondito",
    "header.tabDichiarazioni": "Dichiarazioni",
    "header.tabDicPanoramica": "Dichiarazioni accessibilità",
    "header.tabDicSiti": "Dichiarazioni siti web",
    "header.tabDicApp": "Dichiarazione app",
    "header.tabObiettivi": "Obiettivi",
    "header.tabProgetto": "Il progetto",
    "header.tabEsploraProgetto": "Il progetto di monitoraggio",
    "header.tabCronologia": "Cronologia del progetto",
    "header.tabOpenData": "Open Data",
  },
  en: {
    "header.agid": "Agenzia per l’Italia Digitale",
    "header.agidLink": "https://www.agid.gov.it/en",
    "header.language": "Language selection",
    "header.selectedLanguage": "ENG",
    "header.logo": "/logo/Logo Dash Ext ENG.svg",
    "header.monitoraggio": "Accessibility Monitoring website logo",
    "header.monitoraggioBadge": "beta",
    "header.tabHome": "Home",
    "header.tabMonitoraggio": "Monitoring",
    "header.tabMonSemplificato": "Simplified monitoring",
    "header.tabMonApprofondito": "In-depth monitoring",
    "header.tabErrori": "Errors",
    "header.tabErrSemplificato": "Simplified error monitoring",
    "header.tabErrApprofondito": "In-depth error monitoring",
    "header.tabDichiarazioni": "Statements",
    "header.tabDicPanoramica": "Accessibility statements",
    "header.tabDicSiti": "Website statements",
    "header.tabDicApp": "App statement",
    "header.tabObiettivi": "Objectives",
    "header.tabProgetto": "The project",
    "header.tabEsploraProgetto": "The monitoring project",
    "header.tabCronologia": "Project timeline",
    "header.tabOpenData": "Open Data",
  },
};
