export default {
  it: {
    "header.agid": "Agenzia per l’Italia Digitale",
    "header.agidLink": "https://www.agid.gov.it/", 
    "header.language": "Selezione lingua",
    "header.selectedLanguage": "ITA",
    "header.monitoraggio": "Monitoraggio Accessibilità",
    "header.monitoraggioBadge": "beta",
    "header.tabHome": "Home",
    "header.tabMonitoraggio": "Monitoraggio",
    "header.tabMonSemplificato": "Monitoraggio semplificato",
    "header.tabMonApprofondito": "Monitoraggio approfondito",
    "header.tabErrori": "Errori",
    "header.tabErrSemplificato": "Errori monitoraggio semplificato",
    "header.tabErrApprofondito": "Errori monitoraggio approfondito",
    "header.tabDichiarazioni": "Dichiarazioni",
    "header.tabDicSiti": "Dichiarazioni siti",
    "header.tabDicApp": "Dichiarazioni app",
    "header.tabObiettivi": "Obiettivi",
    "header.tabProgetto": "Il progetto",
    "header.tabCronologia": "Cronologia del progetto",
    "header.tabOpenData": "Open Data",
  },
  en: {
    "header.agid": "Agenzia per l’Italia Digitale",
    "header.agidLink": "https://www.agid.gov.it/en", 
    "header.language": "Language selection",
    "header.selectedLanguage": "ENG",
    "header.monitoraggio": "Accessibility Monitoring",
    "header.monitoraggioBadge": "beta",
    "header.tabHome": "Home",
    "header.tabMonitoraggio": "Monitoring",
    "header.tabMonSemplificato": "Simplified monitoring",
    "header.tabMonApprofondito": "In-depth monitoring",
    "header.tabErrori": "Errors",
    "header.tabErrSemplificato": "Simplified error monitoring",
    "header.tabErrApprofondito": "In-depth error monitoring",
    "header.tabDichiarazioni": "Statements",
    "header.tabDicSiti": "Website statements",
    "header.tabDicApp": "App statements",
    "header.tabObiettivi": "Objectives",
    "header.tabProgetto": "The project",
    "header.tabCronologia": "Project timeline",
    "header.tabOpenData": "Open Data",
  },
};
