export default {
  it: {
    "moniDettaglio.title": "Il monitoraggio in dettaglio",
    "moniDettaglio.downloadSemp": "Il monitoraggio -semplificato- in dettaglio",
    "moniDettaglio.downloadAppr": "Il monitoraggio -approfondito- in dettaglio",
    "moniDettaglio.description":
      "La tabella riporta i <span class='fw-semibold'>dati</span> del monitoraggio <span class='fw-semibold'>semplificato</span> (dati su base trimestrale) e <span class='fw-semibold'>approfondito</span> (dati su base annuale) relativi al periodo <span class='fw-semibold'>gennaio {{firstDate}} - {{lastDate}}</span>. <br/> Per il monitoraggio semplicato sono disponibili ulteriori dettagli nei formati CVS e PDF.",
    "moniDettaglio.semplificato": "Semplificato",
    "moniDettaglio.approfondito": "Approfondito",
    "moniDettaglio.siti": "Siti web valutati",
    "moniDettaglio.pagine": "Pagine web valutate",
    "moniDettaglio.pdf": "Documenti PDF valutati",
    "moniDettaglio.app": "App valutate",
    "moniDettaglio.anno": "Anno",
    "moniDettaglio.trimestre": "Trimestre",
    "moniDettaglio.quarter": "trimestre",
    "moniDettaglio.dettaglio": "Dettaglio per anno",
    "moniDettaglio.dettSiti": "Dettaglio per anno siti web",
    "moniDettaglio.dettPag": "Dettaglio per anno pagine web",
    "moniDettaglio.dettApp": "Dettaglio per anno app",
    "moniDettaglio.dettPdf": "Dettaglio per anno documenti PDF",
  },
  en: {
    "moniDettaglio.title": "Monitoring in detail",
    "moniDettaglio.downloadSemp": "Monitoring -simplified- in detail",
    "moniDettaglio.downloadAppr": "Monitoring -in depth- in detail",
    "moniDettaglio.description":
      "The table shows <span class='fw-semibold'>data</span> from <span class='fw-semibold'>simplified</span> monitoring (quarterly data) and <span class='fw-semibold'>in-depth</span> monitoring (annual data) for the period <span class='fw-semibold'>January {{firstDate}} - {{lastDate}}</span>. <br/> Further details for simplified monitoring are available in CVS and PDF formats.",
    "moniDettaglio.semplificato": "Simplified",
    "moniDettaglio.approfondito": "In-depth",
    "moniDettaglio.siti": "Evaluated websites",
    "moniDettaglio.pagine": "Evaluated web pages",
    "moniDettaglio.pdf": "Evaluated PDF documents",
    "moniDettaglio.app": "Evaluated apps",
    "moniDettaglio.anno": "Year",
    "moniDettaglio.trimestre": "Quarter",
    "moniDettaglio.quarter": "quarter",
    "moniDettaglio.dettaglio": "Detail by year",
    "moniDettaglio.dettSiti": "Websites detail by year",
    "moniDettaglio.dettPag": "Web pages detail by year",
    "moniDettaglio.dettApp": "App detail by year",
    "moniDettaglio.dettPdf": "PDF documents detail by year",
  },
};
