export default {
  it: {
    "moniDettaglio.title": "Il monitoraggio in dettaglio",
    "moniDettaglio.downloadSemp": "Il monitoraggio -semplificato- in dettaglio",
    "moniDettaglio.downloadAppr": "Il monitoraggio -approfondito- in dettaglio",
    "moniDettaglio.description":
      "La tabella mostra i dati del monitoraggio semplificato e approfondito calcolati per anno, dal 2023 ad oggi. I dati del monitoraggio semplificato sono disponibili anche per trimestre.",
    "moniDettaglio.semplificato": "Semplificato",
    "moniDettaglio.approfondito": "Approfondito",
    "moniDettaglio.siti": "Siti web valutati",
    "moniDettaglio.pagine": "Pagine web valutate",
    "moniDettaglio.pdf": "Documenti PDF valutati",
    "moniDettaglio.app": "App valutate",
    "moniDettaglio.totale": "(valori totali)",
    "moniDettaglio.anno": "Anno",
    "moniDettaglio.trimestre": "Trimestre",
    "moniDettaglio.trimestre1": "Primo trimestre",
    "moniDettaglio.trimestre2": "Secondo trimestre",
    "moniDettaglio.trimestre3": "Terzo trimestre",
    "moniDettaglio.trimestre4": "Quarto trimestre",
    "moniDettaglio.dettAnno": "Dettaglio per anno",
    "moniDettaglio.dettTrimestre": "Dettaglio per trimestre",
  },
  en: {
    "moniDettaglio.title": "Monitoring in detail",
    "moniDettaglio.downloadSemp": "Monitoring -simplified- in detail",
    "moniDettaglio.downloadAppr": "Monitoring -in depth- in detail",
    "moniDettaglio.description":
      "The table shows simplified and in-depth monitoring data calculated by year, from 2023 to today. Simplified monitoring data is also available by quarter.",
    "moniDettaglio.semplificato": "Simplified",
    "moniDettaglio.approfondito": "In-depth",
    "moniDettaglio.siti": "Evaluated websites",
    "moniDettaglio.pagine": "Evaluated web pages",
    "moniDettaglio.pdf": "Evaluated PDF documents",
    "moniDettaglio.app": "Evaluated apps",
    "moniDettaglio.totale": "(total values)",
    "moniDettaglio.anno": "Year",
    "moniDettaglio.trimestre": "Quarter",
    "moniDettaglio.trimestre1": "First quarter",
    "moniDettaglio.trimestre2": "Second quarter",
    "moniDettaglio.trimestre3": "Third quarter",
    "moniDettaglio.trimestre4": "Fourth quarter",
    "moniDettaglio.dettAnno": "Detail by year",
    "moniDettaglio.dettTrimestre": "Detail by quarter",
  },
};
