export default {
  it: {
    "moniMainCard.titleSemp": "Monitoraggio semplificato",
    "moniMainCard.titleApp": "Monitoraggio approfondito",
    "moniMainCard.latestUpdate": "Ultimo aggiornamento dati: {{ultimoAggiornamento}}",
    "moniMainCard.subtitleSemp": "Dati prodotti dal monitoraggio automatizzato dell'accessibilità",
    "moniMainCard.subtitleApp": "Dati prodotti dal monitoraggio manuale dell'accessibilità",
    "moniMainCard.descriptionSemp": "Tramite il monitoraggio semplificato è possibile analizzare autonomamente l’accessibilità dei siti web e PDF sui livelli di accessibilità A e AA, obbligatori per legge. Questo tipo di analisi automatizzata permette di ottenere dei risultati attraverso la scansione del codice sorgente ed il contenuto presente nei rispettivi supporti. {{doubleBreak}} I sistemi automatizzati riescono a valutare un sottoinsieme di criteri di successo, riducendo al minimo l'intervento umano necessario per il processo di valutazione.  {{doubleBreak}} La frequenza dei monitoraggi automatici condotti da Mauve è trimestrale.",
    "moniMainCard.descriptionApp": "L'Agenzia per l'Italia Digitale (AGID) conduce anche monitoraggi approfonditi sui servizi della PA suddivisi in siti web, PDF e APP tramite un team di esperti di accessibilità che verifica che i servizi soddisfino tutte le prescrizioni individuate nelle norme e nelle specifiche tecniche dell'articolo 6 della Direttiva UE 2016/2102. {{doubleBreak}} Gli esperti utilizzano diversi strumenti e metodologie come gli screen reader o la navigazione da tastiera e l’analisi del codice web per identificare gli errori. {{doubleBreak}} Il monitoraggio approfondito necessita di più tempo rispetto a quello semplificato, pertanto viene effettuato con frequenza annuale tra il 1° gennaio e il 22 dicembre come espresso dalla normativa europea di riferimento.",
    "moniMainCard.cardTitle1": "Siti valutati",
    "moniMainCard.cardTitle2": "Pagine valutate",
    "moniMainCard.cardTitle3": "PA con almeno un sito valutato",
    "moniMainCard.cardCaption": "Ultimo aggiornamento: {{aggiornamento}}",
  },
  en: {
    "moniMainCard.titleSemp": "Simplified monitoring",
    "moniMainCard.titleApp": "In-depth monitoring",
    "moniMainCard.latestUpdate": "Last data update: {{ultimoAggiornamento}}",
    "moniMainCard.subtitleSemp": "Data produced by automated accessibility monitoring",
    "moniMainCard.subtitleApp": "Data produced by manually accessibility monitoring",
    "moniMainCard.descriptionSemp": "Through simplified monitoring it is possible to independently analyze the accessibility of websites and PDFs on accessibility levels A and AA, mandatory by law. This type of automated analysis allows to obtain results by scanning the source code and the content present in the respective supports. {{doubleBreak}} Automated systems are able to evaluate a subset of success criteria, minimizing the human intervention necessary for the evaluation process. {{doubleBreak}} The frequency of automatic monitoring conducted by Mauve is quarterly.",
    "moniMainCard.descriptionApp": "AGID (Agenzia per l'Italia Digitale) also conducts in-depth monitoring of PA services divided into websites, PDFs and APPs through a team of accessibility experts who verify that the services satisfy all the requirements identified in the standards and specifications techniques of Article 6 of EU Directive 2016/2102. {{doubleBreak}} Experts use different tools and methodologies such as screen readers or keyboard navigation and web code analysis to identify errors. {{doubleBreak}} In-depth monitoring requires more time than simplified monitoring, therefore it is carried out annually between January 1st and December 22nd as expressed by the relevant European legislation.",
    "moniMainCard.cardTitle1": "Evaluated websites",
    "moniMainCard.cardTitle2": "Evaluated pages",
    "moniMainCard.cardTitle3": "PA with at least one site evaluated",
    "moniMainCard.cardCaption": "Last update {{aggiornamento}}",
  },
};
