export default {
  it: {
    "homepage.pagename": "Monitoraggio Accessibilità",
    "homepage.latestUpdate": "Ultimo aggiornamento ",
    "homepage.alert": "Questo sito verrà spostato a breve sul nuovo indirizzo ",
    "homepage.monitoraggioTitle": "Monitoraggio accessibilità",
    "homepage.monitoraggioSubtitle": "Monitorare l’accessibilità permette di intervenire per rendere le informazioni fruibili a tutti, senza discriminazioni.",
    "homepage.monitoraggioParagraphPt1": "Tramite un progetto condiviso tra AgID e il CNR è stato implementato un sistema automatizzato che supporta il",
    "homepage.monitoraggioSempLink": "monitoraggio di accessibilità semplificato",
    "homepage.monitoraggioParagraphPt2": " dei siti delle PA e dei PDF messi a disposizione all’interno dei servizi web. {{break}} Le informazioni prodotte dal monitoraggio automatizzato vengono arricchite con ulteriori dettagli acquisiti dal sito Indice PA e ISTAT. {{doubleBreak}} Oltre al monitoraggio semplificato, AgID svolge il ",
    "homepage.monitoraggioAppLink": "monitoraggio approfondito",
    "homepage.monitoraggioParagraphPt3": " dei siti web, dei PDF e delle APP delle PA condotto manualmente da esperti di accessibilità.",
    "homepage.monitoraggioCardTitle": "Pagine web valutate",
    "homepage.monitoraggioCard3Title": "Siti valutati",
    "homepage.monitoraggioCard2Title": "PDF valutati",
    "homepage.erroriTitle": "Errori di accessibilità",
    "homepage.erroriSubtitle": "Gli errori di accessibilità identificabili",
    "homepage.erroriParagraphPt1": "Le",
    "homepage.erroriParagraphPt2": "sono le linee guida pubblicate dal W3C (World Wide Web Consortium) e definiscono i principi per la creazione di siti web accessibili a tutti, comprese le persone con disabilità. Il sistema di valutazione dell'accessibilità dei siti web si basa sulla verifica (sia manuale che automatica) di un insieme di criteri di successo distinti per tre livelli di conformità: A, AA e AAA. A livello normativo il soddisfacimento dei livelli A e AA è obbligatorio. {{doubleBreak}} Gli ",
    "homepage.erroriParagraphPt3": "errori del monitoraggio semplificato",
    "homepage.erroriParagraphPt4": "vengono identificati dal sistema automatico",
    "homepage.erroriParagraphPt5": ", in grado di analizzare autonomamente {{totErrori}} dei 50 criteri di successo per la valutazione dell’accessibilità dei siti della PA, appartenenti ai livelli A e AA. {{doubleBreak}} Gli ",
    "homepage.erroriParagraphPt6": "errori del monitoraggio approfondito",
    "homepage.erroriParagraphPt7": "vengono identificati tramite un’analisi manuale condotta dagli esperti di accessibilità su tutti i 50 criteri di successo previsti per i siti web e su tutti i 41 criteri di successo previsti per le APP.",
    "homepage.erroriWCAGLink": "https://www.w3.org/Translations/WCAG21-it/",
    "homepage.erroriMAUVElink": "https://mauve.isti.cnr.it/",
    "homepage.dichiarazioniAGIDlink": "https://www.agid.gov.it/it/design-servizi/accessibilita/dichiarazione-accessibilita",
    "homepage.dichiarazioniTitle": "Dichiarazione di accessibilità",
    "homepage.dichiarazioniSubtitle": "Cos'è la dichiarazione di accessibilità?",
    "homepage.dichiarazioniParagraph": "La dichiarazione di accessibilità è lo strumento attraverso il quale le Amministrazioni effettuano una autovalutazione dello stato di accessibilità di ogni sito web e applicazione mobile di cui sono titolari. {{doubleBreak}} Le dichiarazioni non sono oggetto del processo di monitoraggio ma devono essere compilate e pubblicate per adempimento normativo (9 della Legge n. 4/2004) da ogni singola PA. {{break}} Per ulteriori informazioni: ",
    "homepage.dichiarazioniLink": "Dichiarazione di accessibilità",
    "homepage.dichiarazioniCardTitle": "Totale delle dichiarazioni di accessibilità compilate",
    "homepage.dichiarazioniPageLink": "Scopri le dichiarazioni",
    "homepage.obiettiviTitle": "Obiettivi di accessibilità",
    "homepage.obiettiviSubtitle": "Cosa sono gli obiettivi di accessibilità?",
    "homepage.obiettiviParagraph": "Gli obiettivi di accessibilità delle pubbliche amministrazioni mirano a migliorare l’accessibilità dei servizi web e delle applicazioni mobile di cui sono titolari a tutti i cittadini, indipendentemente dalle loro abilità, affinché possano accedere e fruire dei servizi pubblici in modo equo, efficace e senza discriminazioni. {{doubleBreak}} Gli obiettivi di accessibilità vengono pubblicati dalle Pubbliche Amministrazione obbligatoriamente entro il 31 Marzo di ogni anno. {{break}} Per ulteriori informazioni: ",
    "homepage.obiettiviLink": "Obiettivi di accessibilità",
    "homepage.obiettiviCardTitle": "Totale degli obiettivi di accessibilità dichiarati nel {{anno}}",
    "homepage.obiettiviPageLink": "Scopri gli obiettivi",
    "homepage.obiettiviAGIDlink": "https://www.agid.gov.it/it/design-servizi/accessibilita/obiettivi-accessibilita",

  },
  en: {
    "homepage.pagename": "Accessibility Monitoring",
    "homepage.latestUpdate": "Last update ",
    "homepage.alert": "This site will soon be moved to the new address ",
    "homepage.monitoraggioTitle": "Accessibility monitoring",
    "homepage.monitoraggioSubtitle": "Monitoring accessibility allows for intervention to make information accessible to everyone, without discrimination.",
    "homepage.monitoraggioParagraphPt1": "Through a shared project between AgID and CNR, an automated system has been implemented to support the ",
    "homepage.monitoraggioSempLink": "simplified accessibility monitoring",
    "homepage.monitoraggioParagraphPt2": " of public administration websites and PDFs provided within web services. {{break}} The information generated by the automated monitoring is enriched with additional details acquired from the Indice PA and ISTAT websites. {{doubleBreak}} In addition to simplified monitoring, AgID carries out ",
    "homepage.monitoraggioAppLink": "in-depth monitoring",
    "homepage.monitoraggioParagraphPt3": " of PA websites, PDFs and APPs conducted manually by accessibility experts.",
    "homepage.monitoraggioCardTitle": "Web pages evaluated",
    "homepage.monitoraggioCard3Title": "Evaluated websites",
    "homepage.monitoraggioCard2Title": "PDF evaluated",
    "homepage.erroriTitle": "Accessibility errors",
    "homepage.erroriSubtitle": "Identifiable Accessibility Errors",
    "homepage.erroriParagraphPt1": "The",
    "homepage.erroriParagraphPt2": "are guidelines published by the W3C (World Wide Web Consortium) and define principles for creating websites accessible to everyone, including individuals with disabilities. The website accessibility evaluation system is based on the verification of a set of success criteria, both manually and automatically, categorized into three levels of compliance: A, AA, and AAA. From a regulatory standpoint, meeting levels A and AA is mandatory. {{doubleBreak}} The ",
    "homepage.erroriParagraphPt3": "simplified monitoring errors",
    "homepage.erroriParagraphPt4": " are identified by the automatic system",
    "homepage.erroriParagraphPt5": ", capable of independently analyzing {{totErrori}} of the 50 success criteria for evaluating the accessibility of PA sites, belonging to levels A and AA. {{doubleBreak}} The ",
    "homepage.erroriParagraphPt6": "in-depth monitoring errors",
    "homepage.erroriParagraphPt7": " are identified through a manual analysis conducted by accessibility experts on all 50 success criteria for websites and on all 41 success criteria for APPs.",
    "homepage.erroriWCAGLink": "https://www.w3.org/TR/WCAG21/",
    "homepage.erroriMAUVElink": "https://mauve.isti.cnr.it/",
    "homepage.dichiarazioniAGIDlink": "https://www.agid.gov.it/en/design-servizi/web-accessibility",
    "homepage.dichiarazioniTitle": "Accessibility statement",
    "homepage.dichiarazioniSubtitle": "What is an accessibility statement?",
    "homepage.dichiarazioniParagraph": "The accessibility statement is the tool through which administrations perform a self-assessment of the accessibility status of each website and mobile application they own. {{doubleBreak}} Statements are not subject to the monitoring process but must be completed and published for regulatory compliance (Article 9 of Law No. 4/2004) by each individual public administration. {{break}} For further information:",
    "homepage.dichiarazioniLink": "Accessibility Statement",
    "homepage.dichiarazioniCardTitle": "Total accessibility statements completed",
    "homepage.dichiarazioniPageLink": "Explore the statement",
    "homepage.obiettiviTitle": "Accessibility objectives",
    "homepage.obiettiviSubtitle": "What are accessibility objectives?",
    "homepage.obiettiviParagraph": "The accessibility objectives of public administrations aim to improve the accessibility of the web services and mobile applications they own for all citizens, regardless of their abilities, so that they can access and use public services fairly, effectively, and without discrimination. {{doubleBreak}} Accessibility objectives are mandatory for public administrations to publish by March 31st of each year. {{break}} For further information:",
    "homepage.obiettiviLink": "Accessibility Objectives",
    "homepage.obiettiviCardTitle": "Total accessibility objectives declared in {{anno}}",
    "homepage.obiettiviPageLink": "Explore the objectives",
    "homepage.obiettiviAGIDlink": "https://www.agid.gov.it/en/design-servizi/web-accessibility",
  },
};
