export default {
  it: {
    "layout.skipLink": "Salta al contenuto principale",
    "layout.mailto":
      "Il link aprirà l'applicazione predefinita di posta elettronica",
    "layout.externalLink": "Il link si apre in una nuova finestra",
    "layout.latestUpdate": "Ultimo aggiornamento: ",
    "layout.periodoMonitoraggio": "Periodo di monitoraggio: ",
    "layout.anno": "anno ",
    "breadcrumb.monitoraggioSemp": "Monitoraggio semplificato",
    "breadcrumb.monitoraggioAppr": "Monitoraggio approfondito",
    "breadcrumb.erroriSemp": "Errori monitoraggio semplificato",
    "breadcrumb.erroriAppr": "Errori monitoraggio approfondito",
    "breadcrumb.dichiarazioni": "Dichiarazioni accessibilità",
    "breadcrumb.dichiarazioniSiti": "Dichiarazioni siti web",
    "breadcrumb.dichiarazioniApp": "Dichiarazione app",
    "breadcrumb.obiettivi": "Obiettivi di accessibilità",
    "breadcrumb.openData": "Open Data",
    "breadcrumb.progetto": "Il progetto di monitoraggio",
    "breadcrumb.cronologia": "Cronologia del progetto",
    "breadcrumb.contatti": "Contatti",
    "breadcrumb.media": "Media Policy",
    "breadcrumb.legali": "Note legali",
    "breadcrumb.privacy": "Privacy Policy",
  },
  en: {
    "layout.skipLink": "Skip to main content",
    "layout.mailto": "The link will open your default email application",
    "layout.latestUpdate": "Latest update: ",
    "layout.periodoMonitoraggio": "Monitoring period: ",
    "layout.anno": "year ",
    "layout.externalLink": "The link opens in a new tab",
    "breadcrumb.monitoraggioSemp": "Simplified monitoring",
    "breadcrumb.monitoraggioAppr": "In-depth monitoring",
    "breadcrumb.erroriSemp": "Simplified error monitoring",
    "breadcrumb.erroriAppr": "In-depth error monitoring",
    "breadcrumb.dichiarazioni": "Accessibility statements",
    "breadcrumb.dichiarazioniSiti": "Website statements",
    "breadcrumb.dichiarazioniApp": "App statement",
    "breadcrumb.obiettivi": "Accessibility objectives",
    "breadcrumb.openData": "Open Data",
    "breadcrumb.progetto": "The monitoring project",
    "breadcrumb.cronologia": "Project timeline",
    "breadcrumb.contatti": "Contacts",
    "breadcrumb.media": "Media Policy",
    "breadcrumb.legali": "Legal notes",
    "breadcrumb.privacy": "Privacy Policy",
  },
};
